### PR TITLE
Reduce warning

### PR DESCRIPTION
**Pull request by lachrist**
* Demote/remove the most verbose warnings
* New `%O` format marker that replaces `%e`
* Support for top-level await
* Handle the case where `toString` methods do not actually return a string

### CODE REVIEW

**Comment by kgilpin** [comment]
@lachrist are we logging to a file or to the console? With the scanner I started writing SQL parse warnings to a file instead of the console, and this was well received by users. When a user sees anything error-ish in the console, they generally assume it’s serious. But a log file full of warnings does not provoke the same kind of alarm.

**Comment by lachrist** [comment]
Currently everything is dumped in the stdout. I think NPM logs in a temporary file which is referenced in the console, is this what we want? So by default: warning + info + debug in a log files and error in the console?

**Comment by kgilpin** [comment]
> Currently everything is dumped in the stdout. I think NPM logs in a temporary file which is referenced in the console, is this what we want? So by default: warning + info + debug in a log files and error in the console?

This sounds good to me. Although the user doesn’t always want debug info, even in a log file, right?

**Comment by lachrist** [comment]
@kgilpin as per requested, I added the option to log to a file. By default error-level logs are written to stderr. Both the level of the logging and the destination (eg local file) can be defined in the configuration options. Is this acceptable?

**Comment by kgilpin** [comment]
It sounds good to me. Are the options CLI flags or appmap.yml entries?

**Comment by lachrist** [comment]
For now, the log-file can only be set in `appmap.yml`, I forgot to add a CLI flag. Will do right away.

**Comment by kgilpin** [comment]
Ok great, that will be convenient

**Comment by lachrist** [comment]
Do you have an example from the other agents that I can mimic? Also, keep in mind that the CLI options are much more limited that what you can provide in `appmap.yml`. In the meantime can we merge this? I would like to have it merge before supporting spec `1.7.0`.

**Comment by kgilpin** [comment]
Hi Laurent. So let’s make sure we finish this to 100% before moving on the
new spec 1.7.0.

The two things I have in mind for this to be completed:

- asciinema of “major” options (you decide) so users can see it in action
- doc updates at appland.com

**Comment by lachrist** [comment]
I will add demo here: https://github.com/land-of-apps/appmap-agent-js-demo
The first one is mocha: https://github.com/land-of-apps/appmap-agent-js-demo/blob/main/appmap/demo-mocha.cast

**Review by kgilpin — APPROVED** [review]

**Pull request merged**
