### PR TITLE
fix: default exclusion list

### PR DESCRIPTION
**Pull request by lachrist**

### CODE REVIEW

**Comment by apotterri** [comment]
What problem is this solving? Does it need a new test? (Maybe the answer to the first question will answer the second, too....)

**Comment by lachrist** [comment]
Anonymous and unlabeled functions were not filtered out. Actually it was kind of the reverse. Since there is no change in the logic I did not add unit tests. I did however add an anonymous function in the integration test to check that it was indeed not recorded. @ptrdvrk knows about this, this is why I asked him to review this.

**Comment by lachrist** [comment]
In general, this project is very focused around unit testing rather than integration tests. As it matures I expect the integration test suite to grow. However integration test are slow and kinda hard to setup.

**Comment by lachrist** [comment]
Can we merge this? This is a rather important fix that I publish 4 days ago :)

**Review by apotterri — APPROVED** [review]
Thanks for the clarification. FWIW, the more context you can provide in the a PR, the more people can provide helpful reviews. The more people that can review, the faster you'll get an approval. :)

**Comment by lachrist** [comment]
Yeah I get that. It is just that I'm new that the pull request workflow. It feels slow and it feels like I need to justify the change I make on a code base that I know very well. I need to work on that :)

**Review by ptrdvrk — APPROVED** [review]
LGTM Laurent

**Pull request merged**
